#!/usr/bin/env python3
"""parts_to_svg.py — turn a generated `logos/<name>.ts` part list into a clean,
structured, hand-readable SVG.

Why this exists: `trace_logo.py` emits a TypeScript part list, which is what the
scene consumes but is not something a human or a design tool can open. The flat
SVG this writes is the artefact you LOOK at before animating (SKILL.md step 1),
the thing you hand a designer, and the thing you diff a re-trace against.

It is not a second source of truth — it is generated from the same part list the
scene renders, so if the SVG looks wrong the trace is wrong.

Structure of the output:
  <g id="circuit">  … all circuit parts, outermost detail
  <g id="book">     … the book
  <g id="letter">   … the letterform, drawn last so it sits on top
Every path carries its id and its animation metadata (data-rad, data-ang,
data-area) so the SVG round-trips back to the part list without loss.

Fill is `currentColor` on the root so the mark recolours from CSS/`color` —
or from `--color` here, which sets that one root attribute. Never recolour by
editing 42 paths; the mark is one colour and it lives in one place.

Usage:
  python3 parts_to_svg.py runtime/remotion/src/logos/medhavy.ts -o medhavy.svg
  python3 parts_to_svg.py .../medhavy.ts -o medhavy.svg --color '#0072B2'
"""
from __future__ import annotations

import argparse
import os
import re
import sys

PART_RE = re.compile(
    r"\{id:'(?P<id>[^']+)',role:'(?P<role>[^']+)',"
    r"cx:(?P<cx>-?[\d.]+),cy:(?P<cy>-?[\d.]+),"
    r"ang:(?P<ang>-?[\d.]+),rad:(?P<rad>-?[\d.]+),"
    r"area:(?P<area>\d+),d:'(?P<d>[^']*)'\}"
)

ROLE_ORDER = ["circuit", "book", "letter"]


def parse(ts_path: str):
    src = open(ts_path, encoding="utf-8").read()
    vb = re.search(r"VIEWBOX\s*=\s*'([^']+)'", src)
    tf = re.search(r"TRANSFORM\s*=\s*'([^']+)'", src)
    if not vb or not tf:
        sys.exit(f"{ts_path}: no VIEWBOX/TRANSFORM export found")
    parts = [m.groupdict() for m in PART_RE.finditer(src)]
    if not parts:
        sys.exit(f"{ts_path}: no parts matched — has the generator's format changed?")
    return vb.group(1), tf.group(1), parts


def build(view_box: str, transform: str, parts, name: str, title: str,
          colour: str) -> str:
    _, _, w, h = view_box.split()
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}"',
        f'     width="{w}" height="{h}" role="img"',
        f'     aria-labelledby="{name}-title" color="{colour}" fill="currentColor">',
        f'  <title id="{name}-title">{title}</title>',
        "  <desc>",
        f"    {len(parts)} connected components traced with potrace, grouped by role.",
        "    Generated by skills/make/logo-motion/scripts/parts_to_svg.py from the",
        "    part list the LogoMotion scene animates. Do not hand-edit: re-trace and",
        "    re-generate, or the SVG and the animation will disagree.",
        "    data-rad / data-ang are the part's normalised radius and its angle from",
        "    the mark's centre — the two numbers the assembly stagger runs on.",
        "  </desc>",
        # potrace works in a y-up space and emits the flip as a transform. Keeping
        # it as ONE group transform is lossless; baking it into every path would
        # rewrite 55 KB of coordinates for no gain.
        f'  <g transform="{transform}" stroke="none" shape-rendering="geometricPrecision">',
    ]
    by_role = {}
    for p in parts:
        by_role.setdefault(p["role"], []).append(p)

    for role in ROLE_ORDER + [r for r in by_role if r not in ROLE_ORDER]:
        group = by_role.get(role)
        if not group:
            continue
        out.append(f'    <g id="{role}" data-count="{len(group)}">')
        for p in sorted(group, key=lambda q: -int(q["area"])):
            out.append(
                f'      <path id="{p["id"]}" data-rad="{p["rad"]}" '
                f'data-ang="{p["ang"]}" data-area="{p["area"]}"\n'
                f'            d="{p["d"]}"/>'
            )
        out.append("    </g>")
    out += ["  </g>", "</svg>", ""]
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ts", help="path to runtime/remotion/src/logos/<name>.ts")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--title", default=None)
    ap.add_argument("--color", "--colour", dest="color", default="#1E1E1E",
                    help="value for the root `color` attribute, which every path "
                         "inherits via fill=currentColor. Recolouring the mark is "
                         "ONE attribute — that is the point of currentColor. "
                         "(default: #1E1E1E)")
    args = ap.parse_args()

    name = os.path.splitext(os.path.basename(args.ts))[0]
    view_box, transform, parts = parse(args.ts)
    svg = build(view_box, transform, parts, name,
                args.title or f"{name.capitalize()} — brand mark", args.color)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(svg)
    print(f"{args.out}  {len(parts)} parts  viewBox {view_box}  "
          f"color {args.color}  {os.path.getsize(args.out) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
