"""Build self-contained Manim code and portable archive from promoted geometry."""
from pathlib import Path
import json, pprint, hashlib, zipfile

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'assets/originals-25'
FACTORY='''
def make_original(prop_id, height=3.2, x=0.0, y=0.0):
    """Return native VGroup with .parts and scale-correct .action_vectors."""
    from manim import VGroup, Polygon, VMobject, Circle
    import numpy as np
    if not np.isfinite(height) or height <= 0:
        raise ValueError('height must be positive and finite')
    p = _ST_ORIGINALS_25[prop_id]
    pts = []
    for name, shapes in p['parts'].items():
        dx, dy = p['moves'].get(name, (0, 0))
        for s in shapes:
            q = s.get('pts') or [(s['cx']-s['r'],s['cy']-s['r']), (s['cx']+s['r'],s['cy']+s['r'])]
            pts.extend(q)
            pts.extend((a+dx, b+dy) for a,b in q)
    x0,y0 = min(a for a,b in pts), min(b for a,b in pts)
    x1,y1 = max(a for a,b in pts), max(b for a,b in pts)
    scale = min(height/(y1-y0), 4.8/(x1-x0))
    cx,cy = (x0+x1)/2, (y0+y1)/2
    def point(a,b): return np.array([(a-cx)*scale+x, -(b-cy)*scale+y, 0])
    rig = VGroup()
    rig.parts, rig.action_vectors = {}, {}
    for name, shapes in p['parts'].items():
        part = VGroup()
        for s in shapes:
            if s['kind'] == 'circle':
                mob = Circle(radius=s['r']*scale).move_to(point(s['cx'],s['cy']))
            elif s['kind'] == 'polygon':
                mob = Polygon(*[point(a,b) for a,b in s['pts']])
            else:
                mob = VMobject().set_points_as_corners([point(a,b) for a,b in s['pts']])
            mob.set_fill(s['fill'] if s['fill']!='none' else '#FFFFFF', opacity=0 if s['fill']=='none' else 1)
            mob.set_stroke(s['stroke'] if s['stroke']!='none' else '#FFFFFF', width=s['width']*100, opacity=0 if s['stroke']=='none' else 1)
            part.add(mob)
        rig.parts[name] = part
        rig.add(part)
        if name in p['moves']:
            dx,dy = p['moves'][name]
            rig.action_vectors[name] = np.array([dx*scale, -dy*scale, 0])
    return rig
'''

def main():
    manifest=json.loads((ASSETS/'manifest.json').read_text())
    assert len(manifest['props'])==25
    for p in manifest['props']:
        assert hashlib.sha256((ASSETS/'svg'/f'{p["id"]}.svg').read_bytes()).hexdigest()==p['sha256'],p['id']
    manifest.update(status='approved-for-show-tell',approved_by='Bear',approved_on='2026-10-01',approval_scope='Add these 25 originals to the Show-Tell skill; not film publication or render-gate approval.')
    (ASSETS/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    data={p['id']:{'parts':p['parts'],'moves':p['moves']} for p in manifest['props']}
    template=ROOT/'templates/iso_originals_25.py'
    template.write_text('"""Approved original Show-Tell props. Generated by scripts/build_original_props.py.\nPaste into scenes.py; no sibling files required.\n"""\n_ST_ORIGINALS_25 = '+pprint.pformat(data,sort_dicts=False,width=120)+'\n'+FACTORY)
    archive_path=ROOT/'assets/show-tell-originals-25.zip'
    with zipfile.ZipFile(archive_path,'w',zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(ASSETS.rglob('*')):
            if path.is_file():archive.write(path,'assets/originals-25/'+str(path.relative_to(ASSETS)))
        for rel in ['templates/iso_originals_25.py','reference/original-props-25.md','scripts/build_original_props.py','scripts/test_original_props.py']:
            archive.write(ROOT/rel,rel)
    with zipfile.ZipFile(archive_path) as archive:assert archive.testzip() is None
    print('Built approved template and ZIP; verified all 25 SVG hashes.')

if __name__=='__main__':main()
